
database:
  type: "SQLITE"

  sqlite:
    file: "data.db"

  mysql:
    host: "localhost"
    port: 3306
    database: "ahowtofish"
    username: "root"
    password: ""
    useSSL: false
    pool-size: 10
